### ISSUE TITLE
config=>configs

### ISSUE THREAD

**Issue by nibuiro** [jokertennis/optim_22_app#6]
configsが通例らしいので対応お願いします。
ディレクトリ名変更のためにプルリクするのも大げさなので...
すみません。

**Comment by jokertennis** [comment]
わかりました！

**Comment by nibuiro** [comment]
ありがとうございました！

**Comment by jokertennis** [comment]
そういえば、README.mdも変えなければいけないですね。
後、README.mdのテストディレクトリについてですが、自分としてはテスト対象とテストファイルのパッケージ名を同一にするためにも、テストディレクトリを作らないほうが良いのではと思い、削除していました。
石森さんはどう思いますか？
